- hosts: localhost
  connection: local
  tasks:
    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew packages
      homebrew: name="{{ item }}" state=latest
      with_items:
        - nkf
        - wget
        - imagemagick
        - ghostscript
        - lv
        - ag
        - gnupg2
